import {createStore} from "redux";
import applicationReducer from "../reducers/application-reducer";

const initialState = {
    loggedIn: false,
    activeProfile : {
        id: "1",
        background: "https://coolbackgrounds.io/images/backgrounds/white/pure-white-background-85a2a7fd.jpg",
        emailId: 'test@email.com',
        points: 0,
        soundEnabled: true,
        username: 'Max',
        password: 'password',
        chores: [
            {
                id: "1",
                done: false,
                choreName: 'Call Anne about the party',
                dueDate: "2021-04-07T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-03-15T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "2",
                done: false,
                choreName: "Don't smoke",
                dueDate: "2021-04-07T00:00:00.000Z",
                repeatChore: "Daily",
                choreInstructions: "Call before 6PM",
                rewards: {points: false, realLifeItem: true},
                points: 0,
                realLifeItem: "Cookie per day",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "3",
                done: false,
                choreName: 'Practice piano',
                dueDate: "2021-04-03T00:00:00.000Z",
                repeatChore: "Weekly",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "snack",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-02-01T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "4",
                done: false,
                choreName: 'Successfully bench 100lbs',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "Pizza night",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "5",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "6",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "7",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "8",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "9",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            }]
    },
    showCompleted: false,
    profiles : [{
        id: "1",
        background: "https://coolbackgrounds.io/images/backgrounds/white/pure-white-background-85a2a7fd.jpg",
        emailId: 'test@email.com',
        points: 0,
        soundEnabled: true,
        username: 'Max',
        password: 'password',
        chores: [
            {
                id: "1",
                done: false,
                choreName: 'Call Anne about the party',
                dueDate: "2021-04-07T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-03-15T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "2",
                done: false,
                choreName: "Don't smoke",
                dueDate: "2021-04-07T00:00:00.000Z",
                repeatChore: "Daily",
                choreInstructions: "Call before 6PM",
                rewards: {points: false, realLifeItem: true},
                points: 0,
                realLifeItem: "Cookie per day",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "3",
                done: false,
                choreName: 'Practice piano',
                dueDate: "2021-04-03T00:00:00.000Z",
                repeatChore: "Weekly",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "snack",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-02-01T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "4",
                done: false,
                choreName: 'Successfully bench 100lbs',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "Pizza night",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "5",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "6",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "7",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "8",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "9",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-04-04T00:00:00.000Z",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            }]
    },
        {
            id: "2",
            background: "https://coolbackgrounds.io/images/backgrounds/white/pure-white-background-85a2a7fd.jpg",
            emailId: 'jess@email.com',
            points: 0,
            soundEnabled: true,
            username: 'Jessie',
            password: 'password',
            chores: [
                {
                    id: "1",
                    done: false,
                    choreName: 'Call Anne about the party',
                    dueDate: "2021-04-07T00:00:00.000Z",
                    repeatChore: "Never",
                    choreInstructions: "Call before 6PM",
                    rewards: {points: true, realLifeItem: false},
                    points: 20,
                    realLifeItem: "",
                    splitReward: {everyoneGetsReward: false, fcfs: false},
                    dateAdded: "2021-03-15T00:00:00.000Z",
                    assignor: "Jessie",
                    assignees: ["Jessie"],
                    group: "Personal Chores"
                },
                {
                    id: "2",
                    done: false,
                    choreName: "Don't smoke",
                    dueDate: "2021-04-07T00:00:00.000Z",
                    repeatChore: "Daily",
                    choreInstructions: "Call before 6PM",
                    rewards: {points: false, realLifeItem: true},
                    points: 0,
                    realLifeItem: "Cookie per day",
                    splitReward: {everyoneGetsReward: true, fcfs: false},
                    dateAdded: "2025-03-23T00:00:00.000Z",
                    assignor: "Jessie",
                    assignees: ["Jessie"],
                    group: "Personal Chores"
                },
                {
                    id: "3",
                    done: false,
                    choreName: 'Practice piano',
                    dueDate: "2021-04-03T00:00:00.000Z",
                    repeatChore: "Weekly",
                    choreInstructions: "Call before 6PM",
                    rewards: {points: true, realLifeItem: false},
                    points: 20,
                    realLifeItem: "snack",
                    splitReward: {everyoneGetsReward: false, fcfs: false},
                    dateAdded: "2021-02-01T00:00:00.000Z",
                    assignor: "Jessie",
                    assignees: ["Jessie"],
                    group: "Personal Chores"
                }]
        }],
    activeGroupId : "Personal Chores",
    groups : [{
        id: "1",
        name: 'Family',
        progressBar: false,
        members: ["Marie", "Abby", "Vinnie", "Alan", "Max"],
        chores: [
            {
                id:"1",
                done:false,
                choreName: 'Vacuum',
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:5,
                realLifeItem:"",
                dueDate: "2021-04-05T00:00:00.000Z",
                splitReward:{everyoneGetsReward:true,fcfs:false},
                dateAdded: "2021-03-23T00:00:00.000Z",
                assignor: "Marie",
                assignees: ["Marie"],
                group: "1"
            },
            {
                id:"2",
                done:false,
                choreName: 'Finish laundry',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:20,
                realLifeItem:"",
                splitReward:{everyoneGetsReward:true,fcfs:false},
                dateAdded: "2021-03-30T00:00:00.000Z",
                assignor: "Vinnie",
                assignees: ["Max"],
                group: "1"
            },

            {
                id:"3",
                done:false,
                choreName: 'Take out the trash',
                dueDate: "2025-03-23T00:00:00.000Z",
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:5,
                realLifeItem:"",
                splitReward:{everyoneGetsReward:false,fcfs:false},
                dateAdded: "2025-03-23T00:00:00.000Z",
                assignor: "Max",
                assignees: ['Vinnie'],
                group: "1"
            }
        ]
    },
        {
            id: "2",
            name: 'Group Project',
            progressBar: true,
            members: ['Chad', 'Brian', "Max"],
            chores: [
                {
                    id:"1",
                    done:false,
                    choreName: 'Write documentation',
                    dueDate: "2021-04-23T00:00:00.000Z",
                    repeatChore: "Never",
                    choreInstructions: "",
                    rewards:{points:true,realLifeItem:false},
                    points:20,
                    realLifeItem:"",
                    splitReward:{everyoneGetsReward:false,fcfs:true},
                    dateAdded: "2025-04-01T00:00:00.000Z",
                    assignor: "Chad",
                    assignees: ["Max"],
                    group: "2"
                },

                {
                    id:"2",
                    done:false,
                    choreName: 'Test section 3',
                    dueDate: "2021-04-12T00:00:00.000Z",
                    repeatChore: "Never",
                    choreInstructions: "",
                    rewards:{points:true,realLifeItem:false},
                    points:5,
                    realLifeItem:"",
                    splitReward:{everyoneGetsReward:false,fcfs:true},
                    dateAdded: "2021-04-02T00:00:00.000Z",
                    assignor: "Brian",
                    assignees: ["Max"],
                    group: "2"
                }]
        },
        {
            id: "3",
            name: 'test',
            progressBar: false,
            members: ["Marie", "Abby", "Vinnie", "Alan", "Max"],
            chores: []
        },
        {
            id: "4",
            name: 'test2',
            progressBar: false,
            members: ["Jessie", "Max"],
            chores: []
        },
        {
            id: "5",
            name: 'test3',
            progressBar: false,
            members: ["Marie", "Abby", "Vinnie", "Alan", "Max"],
            chores: []
        }
    ]
}

let applicationStore = createStore(applicationReducer, initialState)

export default applicationStore;