import {createStore} from "redux";
import applicationReducer from "../reducers/application-reducer";

const initialState = {
    loggedIn: false,
    activeProfile : {
        id: "1",
        background: "/cool-background-white.png",
        emailId: 'max@gmail.com',
        points: 0,
        soundEnabled: true,
        username: 'Max',
        password: 'maxpassword',
        chores: [
            {
                id: "1",
                done: false,
                choreName: 'Call Anne about the party',
                dueDate: "2021-04-28",
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-15",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "2",
                done: false,
                choreName: "Go Grocery Shopping",
                dueDate: "2021-04-23",
                repeatChore: "Never",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "3",
                done: false,
                choreName: 'Practice piano',
                dueDate: "2021-04-27",
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "snack",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-02-01",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "4",
                done: false,
                choreName: 'Successfully bench 100lbs',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "Pizza night",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "5",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-05-04",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: false, realLifeItem: false},
                points: 0,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            }]
    },
    showCompleted: false,
    profiles : [{
        id: "1",
        background: "/cool-background-white.png",
        emailId: 'max@gmail.com',
        points: 0,
        soundEnabled: true,
        username: 'Max',
        password: 'maxpassword',
        chores: [
            {
                id: "1",
                done: false,
                choreName: 'Call Anne about the party',
                dueDate: "2021-04-28",
                repeatChore: "Never",
                choreInstructions: "Call before 6PM",
                rewards: {points: true, realLifeItem: false},
                points: 20,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-03-15",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "2",
                done: false,
                choreName: "Go Grocery Shopping",
                dueDate: "2021-04-23",
                repeatChore: "Never",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: false},
                points: 10,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "3",
                done: false,
                choreName: 'Practice piano',
                dueDate: "2021-04-27",
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "snack",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2021-02-01",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "4",
                done: false,
                choreName: 'Successfully bench 100lbs',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "",
                rewards: {points: true, realLifeItem: true},
                points: 20,
                realLifeItem: "Pizza night",
                splitReward: {everyoneGetsReward: true, fcfs: false},
                dateAdded: "2025-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            },
            {
                id: "5",
                done: false,
                choreName: 'Read Chapter 14',
                dueDate: "2021-05-04",
                repeatChore: "Never",
                choreInstructions: "Online textbook",
                rewards: {points: false, realLifeItem: false},
                points: 0,
                realLifeItem: "",
                splitReward: {everyoneGetsReward: false, fcfs: false},
                dateAdded: "2021-03-23",
                assignor: "Max",
                assignees: ["Max"],
                group: "Personal Chores"
            }]
    }],
    activeGroupId : "Personal Chores",
    groups : [{
        id: "1",
        name: 'Family',
        progressBar: true,
        members: ["Marie", "Abby", "Vinnie", "Alan", "Max"],
        chores: [
            {
                id:"1",
                done:false,
                choreName: 'Vacuum',
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:5,
                realLifeItem:"",
                dueDate: "2021-04-29",
                splitReward:{everyoneGetsReward:true,fcfs:false},
                dateAdded: "2021-03-23",
                assignor: "Marie",
                assignees: ["Marie"],
                group: "1"
            },
            {
                id:"2",
                done:false,
                choreName: 'Finish laundry',
                dueDate: null,
                repeatChore: "Never",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:20,
                realLifeItem:"",
                splitReward:{everyoneGetsReward:true,fcfs:false},
                dateAdded: "2021-04-28",
                assignor: "Vinnie",
                assignees: ["Max"],
                group: "1"
            },

            {
                id:"3",
                done:true,
                choreName: 'Take out the trash',
                dueDate: "2025-04-30",
                repeatChore: "Weekly",
                choreInstructions: "",
                rewards:{points:true,realLifeItem:false},
                points:5,
                realLifeItem:"",
                splitReward:{everyoneGetsReward:false,fcfs:false},
                dateAdded: "2025-03-23",
                assignor: "Max",
                assignees: ['Vinnie', 'Abby'],
                group: "1"
            }
        ]
    },
        {
            id: "2",
            name: 'Group Project',
            progressBar: true,
            members: ['Chad', 'Brian', "Max"],
            chores: [
                {
                    id:"1",
                    done:false,
                    choreName: 'Write documentation',
                    dueDate: "2021-04-23",
                    repeatChore: "Never",
                    choreInstructions: "",
                    rewards:{points:true,realLifeItem:false},
                    points:20,
                    realLifeItem:"",
                    splitReward:{everyoneGetsReward:false,fcfs:true},
                    dateAdded: "2025-04-01",
                    assignor: "Chad",
                    assignees: ["Max"],
                    group: "2"
                },
                {
                    id:"2",
                    done:false,
                    choreName: 'Test section 3',
                    dueDate: "2021-04-12",
                    repeatChore: "Never",
                    choreInstructions: "",
                    rewards:{points:true,realLifeItem:false},
                    points:5,
                    realLifeItem:"",
                    splitReward:{everyoneGetsReward:false,fcfs:true},
                    dateAdded: "2021-04-02",
                    assignor: "Brian",
                    assignees: ["Max"],
                    group: "2"
                }]
        }
    ]
}

let applicationStore = createStore(applicationReducer, initialState)

export default applicationStore;